
version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - NODE_ENV=production
    networks:
      - aqua-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - ./api/data:/app/data
      - ./api/logs:/app/logs
    # Make sure it listens on all interfaces
    environment:
      - PORT=3001
      - NODE_ENV=production
    networks:
      - aqua-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Add healthcheck to verify the API is responsive
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  arduino-reader:
    build:
      context: ./arduino-reader
      dockerfile: Dockerfile
    restart: unless-stopped
    privileged: true  # Needed for USB access
    volumes:
      - ./arduino-reader/logs:/app/logs
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - ARDUINO_SERIAL_PORT=/dev/ttyUSB0
      - ARDUINO_BAUD_RATE=9600
      - API_URL=http://api:3001/api/readings
      - READ_INTERVAL=5
    depends_on:
      - api
    networks:
      - aqua-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  aqua-network:
    driver: bridge
